/* ═══════════════════════════════════════════════════════════
   PhotoCoach — Scene Definitions (42 scenes)
   ═══════════════════════════════════════════════════════════ */

const ISO_STOPS       = [100, 200, 400, 800, 1600, 3200, 6400, 12800];
const APERTURE_STOPS  = [1.4, 2, 2.8, 4, 5.6, 8, 11, 16, 22];
const SHUTTER_STOPS   = [30, 15, 8, 4, 2, 1, 0.5, 0.25, 0.125, 1/15, 1/30, 1/60, 1/125, 1/250, 1/500, 1/1000];
const SHUTTER_LABELS  = ['30s','15s','8s','4s','2s','1s','1/2','1/4','1/8','1/15','1/30','1/60','1/125','1/250','1/500','1/1000'];
const WB_STOPS        = [3000, 3500, 4500, 5500, 6500, 7500, 9000];
const WB_LABELS       = ['3000K', '3500K', '4500K', '5500K', '6500K', '7500K', '9000K'];

const SCENES = [
    // ── Original 12 ─────────────────────────────────────────
    {
        id: 'golden_hour_landscape',
        title: 'Golden Hour Hills',
        category: 'Landscape',
        description: 'Capture this golden hour landscape. Use a small aperture for edge-to-edge sharpness, keep ISO low, and let a slow shutter compensate.',
        image: 'images/landscape_golden_hour.png',
        idealSettings: { iso: 0, aperture: 7, shutter: 7, wb: 4 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Cloudy/Shade (warm)',
        tips: ['Use a tripod for sharp landscape shots at slow shutter speeds','f/11-f/16 gives the deepest, sharpest depth of field','Golden hour light is warm — a slightly warm WB enhances it','Keep ISO at 100 for the cleanest, grain-free image']
    },
    {
        id: 'outdoor_portrait',
        title: 'Natural Light Portrait',
        category: 'Portrait',
        description: 'A portrait in soft natural outdoor light. Use a wide aperture to blur the background and isolate the subject beautifully.',
        image: 'images/portrait_outdoor.png',
        idealSettings: { iso: 1, aperture: 1, shutter: 11, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Wide apertures (f/1.4-f/2.8) create beautiful background blur','Always focus on the eyes in a portrait','Avoid harsh midday sun — soft, diffused light is more flattering','Keep shutter at least 1/60s to avoid camera shake']
    },
    {
        id: 'sports_action',
        title: 'Sports Action Freeze',
        category: 'Sports',
        description: 'Freeze this intense sporting moment. You need a very fast shutter speed — push your ISO if needed.',
        image: 'images/sports_action.png',
        idealSettings: { iso: 3, aperture: 2, shutter: 15, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 2 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Use at least 1/500s to freeze fast action; 1/1000s is ideal','Open your aperture to let in more light at fast shutter speeds','A sharp, noisy photo beats a blurry, clean one','Use continuous AF (AF-C) to track moving subjects']
    },
    {
        id: 'night_cityscape',
        title: 'City Lights at Night',
        category: 'Night',
        description: 'Capture the city skyline at night. Use a long exposure on a tripod for beautiful light trails.',
        image: 'images/night_cityscape.png',
        idealSettings: { iso: 1, aperture: 6, shutter: 1, wb: 2 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 2 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Tungsten/Cool',
        tips: ['A sturdy tripod is essential for night photography','Long exposures (10-30s) create beautiful light trails from traffic','Use a remote shutter or self-timer to prevent camera shake','f/8-f/11 creates star-burst effects on point lights']
    },
    {
        id: 'macro_flower',
        title: 'Macro Flower Detail',
        category: 'Macro',
        description: 'Get an extreme close-up of this flower. In macro photography, even tiny apertures give razor-thin depth of field.',
        image: 'images/macro_flower.png',
        idealSettings: { iso: 2, aperture: 5, shutter: 9, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['In macro, even f/8 gives extremely shallow depth of field','Use a tripod — any movement is dramatically amplified','Focus stacking can give sharpness throughout the subject','Diffused natural light or a ring flash works best for macro']
    },
    {
        id: 'indoor_lowlight',
        title: 'Cozy Café Ambiance',
        category: 'Low Light',
        description: 'Capture the warm atmosphere of this candlelit café. Balance a high ISO for exposure against noise.',
        image: 'images/indoor_lowlight.png',
        idealSettings: { iso: 4, aperture: 1, shutter: 7, wb: 1 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Tungsten (warm)',
        tips: ['Open your aperture as wide as possible in low light','ISO 1600-3200 is acceptable — modern cameras handle it well','Warm white balance preserves the cozy candlelight mood','Brace against a wall or table if no tripod is available']
    },
    {
        id: 'sunset_silhouette',
        title: 'Sunset Silhouette',
        category: 'Silhouette',
        description: 'Create a dramatic silhouette against the sunset sky. Expose for the sky, not the subject.',
        image: 'images/sunset_silhouette.jpg',
        idealSettings: { iso: 0, aperture: 5, shutter: 11, wb: 4 },
        acceptableRange: { iso: 1, aperture: 2, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Shade/Cloudy (warm)',
        tips: ['Meter from the bright sky — the subject will turn dark naturally','A warm white balance enhances sunset colors beautifully','f/8 keeps both the silhouette and sky sharp','Shoot during the "golden 10 minutes" just after sunset']
    },
    {
        id: 'street_rainy',
        title: 'Rainy Street Scene',
        category: 'Street',
        description: 'Capture this moody rainy street with wet reflections and neon lights. Balance exposure across a high dynamic range.',
        image: 'images/street_rainy.jpg',
        idealSettings: { iso: 3, aperture: 3, shutter: 11, wb: 2 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 2 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Auto/Fluorescent',
        tips: ['Wet streets create beautiful reflections — use them compositionally','Keep shutter fast enough to avoid handheld blur','Slightly underexposing preserves the moody atmosphere','Look for puddles that mirror neon signs']
    },
    {
        id: 'waterfall_silky',
        title: 'Silky Waterfall',
        category: 'Long Exposure',
        description: 'Create the classic silky waterfall effect. Use a very slow shutter — f/22 and ISO 100 to make it possible without an ND filter.',
        image: 'images/waterfall.jpg',
        idealSettings: { iso: 0, aperture: 8, shutter: 2, wb: 3 },
        acceptableRange: { iso: 0, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Daylight',
        tips: ['8 seconds turns water into a silky smooth veil','Use the smallest aperture and lowest ISO to slow things down enough','A tripod is absolutely essential','In bright light, use a Neutral Density (ND) filter to allow longer exposures']
    },
    {
        id: 'bird_in_flight',
        title: 'Eagle in Flight',
        category: 'Wildlife',
        description: 'Capture this soaring eagle. Wildlife requires fast shutter speeds to freeze wing movement.',
        image: 'images/bird_flight.jpg',
        idealSettings: { iso: 2, aperture: 3, shutter: 15, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 2 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Use 1/1000s or faster to freeze bird wing movement','Pre-focus on where you expect the bird to fly','Use burst mode to increase your chances','A telephoto lens (300mm+) is typical for bird photography']
    },
    {
        id: 'architecture_modern',
        title: 'Modern Architecture',
        category: 'Architecture',
        description: 'Photograph this striking modern building. Architecture demands maximum sharpness — use the aperture sweet spot.',
        image: 'images/architecture.jpg',
        idealSettings: { iso: 0, aperture: 5, shutter: 9, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Daylight',
        tips: ['f/8-f/11 is the optical "sweet spot" for most lenses','Keep ISO at 100 for maximum detail','Use a tripod and keep the camera level to avoid converging verticals','Shoot during blue hour for dramatic building lighting']
    },
    {
        id: 'beach_bright',
        title: 'Bright Beach Day',
        category: 'Bright Light',
        description: 'Shoot this intense beach scene. White sand reflects a lot of light — careful not to let the meter trick you into underexposure.',
        image: 'images/beach.jpg',
        idealSettings: { iso: 0, aperture: 6, shutter: 13, wb: 3 },
        acceptableRange: { iso: 0, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Daylight',
        tips: ['"Sunny 16" rule: f/16, ISO 100, shutter = 1/ISO','Sand and water are very reflective — watch for overexposure','A polarizing filter reduces glare and enhances colors','Slightly underexpose to preserve bright highlight detail']
    },

    // ── New 30 Scenes ────────────────────────────────────────
    {
        id: 'foggy_forest',
        title: 'Mystic Foggy Forest',
        category: 'Landscape',
        description: 'Fog softens the scene into layers of depth. Use a slow shutter for misty atmosphere, keep ISO low for total cleanliness.',
        image: 'images/foggy_forest.jpg',
        idealSettings: { iso: 1, aperture: 6, shutter: 6, wb: 2 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Fluorescent/Cool',
        tips: ['Fog scatters light — meter carefully to not overexpose','A slow shutter deepens the misty atmosphere','Cool white balance enhances the eerie mood','A tripod is essential for 1s+ shutter speeds']
    },
    {
        id: 'aurora',
        title: 'Aurora Borealis',
        category: 'Night',
        description: 'Photograph the Northern Lights. You need a very long exposure, wide aperture, and high ISO to capture those faint green ribbons.',
        image: 'images/aurora.jpg',
        idealSettings: { iso: 5, aperture: 0, shutter: 0, wb: 5 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 2 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Actual coolish blue',
        tips: ['Use 20-30s exposures to record the aurora','Wide-open aperture (f/1.4-f/2.8) is essential — every photon counts','ISO 3200+ is necessary — noise is preferable to a black photo','A slightly cool WB reveals the natural blue sky behind the aurora']
    },
    {
        id: 'desert_dunes',
        title: 'Desert Dunes at Sunrise',
        category: 'Landscape',
        description: 'The raking light of sunrise casts beautiful shadows across the dunes. Keep everything tack sharp, ISO low.',
        image: 'images/desert_dunes.jpg',
        idealSettings: { iso: 0, aperture: 6, shutter: 8, wb: 4 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Shade/Warm',
        tips: ['Low raking light reveals sand texture and shadow detail','f/11 gives you deep depth of field across distant dunes','A warm WB enhances the golden sand tones','Shoot within 30 minutes of sunrise before harsh shadows appear']
    },
    {
        id: 'snowy_mountain',
        title: 'Snowy Mountain Peak',
        category: 'Landscape',
        description: 'Bright snow is a metering trap — your camera will underexpose trying to turn the snow grey. Compensate by overexposing slightly.',
        image: 'images/snowy_mountain.jpg',
        idealSettings: { iso: 0, aperture: 7, shutter: 12, wb: 3 },
        acceptableRange: { iso: 0, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Daylight',
        tips: ['Snow is very reflective — add +1 to +2 EV exposure compensation','f/16 keeps the entire mountain range sharp','A polarizing filter darkens the blue sky dramatically','Overcast days give even snow detail without harsh shadows']
    },
    {
        id: 'milky_way',
        title: 'Milky Way Night Sky',
        category: 'Night',
        description: 'Photographing the Milky Way means working in total darkness. You need a very wide aperture, high ISO, and the "500 rule" for shutter timing.',
        image: 'images/milky_way.jpg',
        idealSettings: { iso: 5, aperture: 0, shutter: 1, wb: 5 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 2 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Cool/Tungsten',
        tips: ['The "500 Rule": shutter (s) = 500 / focal length to avoid star trails','f/1.4-f/2.8 is essential — wide open for maximum star light','ISO 3200-6400 is typical — embrace the noise','Go as far from city lights as possible']
    },
    {
        id: 'studio_portrait',
        title: 'Low-Key Studio Portrait',
        category: 'Portrait',
        description: 'A dramatic low-key studio portrait with controlled artificial light. The challenge: expose correctly for the lit areas while keeping shadows dark.',
        image: 'images/studio_portrait.jpg',
        idealSettings: { iso: 0, aperture: 3, shutter: 11, wb: 1 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Tungsten',
        tips: ['In a studio, ISO 100 gives the cleanest results','f/4 is a good portrait aperture — sharp face, soft background','1/60s or faster is fine with flash (flash freezes the moment)','Low-key lighting means intentionally dark shadows — resist the urge to overexpose']
    },
    {
        id: 'hummingbird',
        title: 'Hummingbird in Flight',
        category: 'Wildlife',
        description: 'A hummingbird\'s wings beat 50-80 times per second. To freeze them, you need an ultra-fast shutter speed.',
        image: 'images/hummingbird.jpg',
        idealSettings: { iso: 3, aperture: 2, shutter: 15, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 2 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Hummingbird wings need 1/1000s or faster to freeze','Use a flash to achieve ultra-fast effective shutter speeds','Pre-focus on a flower they frequently visit','Wide aperture + high ISO is the combination you need here']
    },
    {
        id: 'fire_performance',
        title: 'Fire Performer',
        category: 'Low Light',
        description: 'Fire dancing happens at night with a single moving light source. Choose your settings carefully: too slow = blur, too fast = underexposed.',
        image: 'images/fire_performance.jpg',
        idealSettings: { iso: 3, aperture: 2, shutter: 12, wb: 0 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Tungsten (very warm)',
        tips: ['1/250s freezes most fire movement while capturing trails','Wide aperture is necessary — fire at night is not that bright','A very warm WB (3000K) makes fire look naturally orange/red','Be careful not to overexpose the center of the flame']
    },
    {
        id: 'food_photo',
        title: 'Food Photography',
        category: 'Still Life',
        description: 'A beautiful flat-lay food shot. Usually done with natural window light. f/4-f/5.6 gives some depth while keeping the dish sharp.',
        image: 'images/food_photo.jpg',
        idealSettings: { iso: 1, aperture: 3, shutter: 9, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Side window light creates attractive shadows and depth','f/4 gives slight depth to a top-down food shot','Diffuse harsh sunlight with a white curtain or reflector','A white card reflector opposite the window fills in harsh shadows']
    },
    {
        id: 'ocean_waves',
        title: 'Ocean Waves (Long Exposure)',
        category: 'Long Exposure',
        description: 'Long exposures turn crashing waves into a dreamy mist. Use a very slow shutter, small aperture, and tripod.',
        image: 'images/ocean_waves.jpg',
        idealSettings: { iso: 0, aperture: 8, shutter: 2, wb: 3 },
        acceptableRange: { iso: 0, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Daylight',
        tips: ['8-30s turns waves into a silky mist around rocks','Use an ND filter to slow the shutter in daylight','Shoot during blue hour when light is naturally dim','A weighted, sturdy tripod is critical — waves create vibrations']
    },
    {
        id: 'autumn_forest',
        title: 'Autumn Forest Path',
        category: 'Landscape',
        description: 'A winding forest path in autumn colors. Keep the whole scene in focus from nearby leaves to distant trees.',
        image: 'images/autumn_forest.jpg',
        idealSettings: { iso: 1, aperture: 6, shutter: 8, wb: 4 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Shade (warm)',
        tips: ['Overcast skies are perfect for forest photography — no harsh shadows','f/11 keeps the entire scene in focus','A slightly warm WB enhances warm orange and red tones','Use a tripod to allow a slow enough shutter at low ISO']
    },
    {
        id: 'lightning',
        title: 'Lightning Strike',
        category: 'Night',
        description: 'To capture lightning, you need a long enough exposure to catch it when it strikes. Use "bulb mode" in real life — here simulate with a very slow shutter.',
        image: 'images/lightning.jpg',
        idealSettings: { iso: 0, aperture: 6, shutter: 1, wb: 2 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 3, wb: 2 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Cool/neutral',
        tips: ['Use "bulb mode" and a remote shutter to keep the shutter open until lightning strikes','f/8-f/11 keeps the scene sharp','ISO 100-200 prevents the background from brightening too much during the long wait','A heavy tripod is essential — any vibration will blur the shot']
    },
    {
        id: 'cathedral',
        title: 'Cathedral Interior',
        category: 'Architecture',
        description: 'Interiors with mixed light (stained glass + ambient) are challenging. A wide aperture and high ISO let you hand-hold without a tripod.',
        image: 'images/cathedral.jpg',
        idealSettings: { iso: 4, aperture: 2, shutter: 9, wb: 1 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Tungsten/Warm',
        tips: ['Interior churches are often very dark — push ISO as needed','A wide aperture lets you handhold without a tripod','Shoot in RAW: the mixed lighting is easier to fix in post','Use a wide-angle lens to capture the full height of the space']
    },
    {
        id: 'motorcycle_race',
        title: 'Motorcycle Racing',
        category: 'Sports',
        description: 'Racing motorcycles are extremely fast. Try "panning" — tracking the bike as it passes — for a sharp subject with a blurred background.',
        image: 'images/motorcycle_race.jpg',
        idealSettings: { iso: 2, aperture: 4, shutter: 10, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 2 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Panning: 1/30-1/60s while tracking the subject = sharp bike, blurred background','Pre-focus on a fixed point and shoot as the bike passes','Use continuous AF to lock onto the rider','f/4-f/5.6 gives you some margin in panning accuracy']
    },
    {
        id: 'coral_reef',
        title: 'Underwater Coral Reef',
        category: 'Underwater',
        description: 'Underwater photography loses red light quickly with depth. A slightly warm WB compensates, and wide aperture lets in the limited available light.',
        image: 'images/coral_reef.jpg',
        idealSettings: { iso: 3, aperture: 2, shutter: 10, wb: 4 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Warm/Shade',
        tips: ['Water absorbs red light — add warm WB or use a red filter','Get as close as possible to reduce water between you and the subject','Underwater strobes restore natural color at depth','Shoot upward towards the sun for backlighting effects']
    },
    {
        id: 'stage_performance',
        title: 'Stage Performance',
        category: 'Low Light',
        description: 'Stage photography means mixed, bright spot lights with dark surroundings. Balance to expose the performer, not the dark background.',
        image: 'images/stage_performance.jpg',
        idealSettings: { iso: 4, aperture: 1, shutter: 12, wb: 0 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 2 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Tungsten (very warm)',
        tips: ['Meter specifically for the spotlight-lit performer, not the dark stage','1/250s or faster freezes mid-performance movements','ISO 1600-3200 is typical for stage work','Auto WB handles mixed stage lights well, or shoot RAW']
    },
    {
        id: 'frost_macro',
        title: 'Frost Crystal Macro',
        category: 'Macro',
        description: 'Intricate ice crystals up close. Macro photography means an extremely thin plane of focus — be precise.',
        image: 'images/frost_macro.jpg',
        idealSettings: { iso: 1, aperture: 5, shutter: 9, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Work quickly — your breath can melt the frost','A tripod is essential: even breathing causes blur at macro distances','f/8 gives the widest usable depth of field in macro','Overcast light is ideal — harsh sun creates glare on ice']
    },
    {
        id: 'hot_air_balloons',
        title: 'Hot Air Balloons',
        category: 'Landscape',
        description: 'Colorful balloons drifting across the sky at sunrise. Expose for the bright sky and balloons, not shadows beneath.',
        image: 'images/hot_air_balloons.jpg',
        idealSettings: { iso: 0, aperture: 5, shutter: 12, wb: 4 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Shade (warm)',
        tips: ['Balloons move slowly — 1/250s is enough to freeze them','Keep aperture around f/8 for sharp balloons across the frame','Sunrise warm light brings out the vivid balloon colors','Slightly underexpose to keep sky rich and not washed out']
    },
    {
        id: 'jazz_concert',
        title: 'Jazz Concert (Low Light)',
        category: 'Low Light',
        description: 'Intimate jazz club photography. The thick, contrasty lighting is beautiful — expose for the musician, let the background go dark.',
        image: 'images/jazz_concert.jpg',
        idealSettings: { iso: 4, aperture: 1, shutter: 11, wb: 1 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Tungsten (warm)',
        tips: ['1/60s is the minimum to freeze most musician movements','The warm tungsten light is part of the mood — use a warm WB','ISO 1600-3200 is expected in these conditions','Never use flash — it ruins the atmosphere and annoys performers']
    },
    {
        id: 'lavender_fields',
        title: 'Lavender Fields',
        category: 'Landscape',
        description: 'Endless rows of purple lavender. Keep the whole field in focus with a small aperture; shoot at golden hour for warm light.',
        image: 'images/lavender_fields.jpg',
        idealSettings: { iso: 0, aperture: 6, shutter: 9, wb: 4 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Shade/Warm',
        tips: ['Shoot at golden hour for warm light on the purple flowers','f/11 keeps the entire field in focus from foreground to horizon','Get low to the ground to emphasize the rows of lavender','A slight warm WB makes the flowers pop against green stems']
    },
    {
        id: 'snow_leopard',
        title: 'Snow Leopard Portrait',
        category: 'Wildlife',
        description: 'A telephoto wildlife portrait. Isolate the subject with a wide aperture while using a fast enough shutter for a sharp, detailed coat.',
        image: 'images/snow_leopard.jpg',
        idealSettings: { iso: 2, aperture: 3, shutter: 13, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Photograph at eye level with the animal when safe to do so','f/4-f/5.6 isolates the animal with beautiful background blur','1/500s ensures the sharpest coat detail even with slight movement','Telephoto lenses compress the background beautifully']
    },
    {
        id: 'neon_city',
        title: 'Neon City Night',
        category: 'Night',
        description: 'A Tokyo-style neon cityscape at night. Handheld street shooting — balance ISO against noise while keeping the shutter fast enough.',
        image: 'images/neon_city.jpg',
        idealSettings: { iso: 3, aperture: 2, shutter: 11, wb: 2 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 2 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Fluorescent',
        tips: ['Lean against walls or poles to stabilize handheld night shots','ISO 800-1600 is usually necessary for neon street photography','A moderate WB lets the neon colors appear vivid and natural','Look for reflections in wet streets to double the visual interest']
    },
    {
        id: 'children_rain',
        title: 'Children Playing in Rain',
        category: 'Street',
        description: 'A joyful candid of children splashing in puddles. Capture genuine emotion — freeze the water splash with a fast shutter.',
        image: 'images/children_rain.jpg',
        idealSettings: { iso: 2, aperture: 3, shutter: 13, wb: 2 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 2 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Overcast',
        tips: ['1/500s or faster freezes water splashes mid-air','Overcast rain light is soft and flattering — use it','Get down to child eye level for more engaging candids','Be patient — capture the genuine laughter, not the posed smile']
    },
    {
        id: 'campfire',
        title: 'Campfire at Night',
        category: 'Low Light',
        description: 'Glowing campfire in the forest at night. The fire is the only light source — expose for the warm firelight on the surrounding people/trees.',
        image: 'images/campfire.jpg',
        idealSettings: { iso: 4, aperture: 2, shutter: 9, wb: 0 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Tungsten (very warm)',
        tips: ['A very warm WB (3000K) makes the firelight look naturally golden','f/2.8 lets in enough light while keeping the fire and nearby people sharp','1/15s blurs dancing flames — increase shutter to 1/60s to freeze them','Face into the fire: light on your subject, fire as the main light source']
    },
    {
        id: 'bicycle_street',
        title: 'Bicycle on Cobblestones',
        category: 'Street',
        description: 'A charming street scene with a bicycle on old cobblestones. Use a moderately wide aperture for depth and character.',
        image: 'images/bicycle_street.jpg',
        idealSettings: { iso: 1, aperture: 3, shutter: 11, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['f/4 gives pleasant depth: sharp bike, blurred background','Look for interesting leading lines created by cobblestone rows','Morning light casts long shadows that add dimension','Include environmental context to tell a story, not just the bike']
    },
    {
        id: 'bonsai_tree',
        title: 'Bonsai Tree Close-Up',
        category: 'Macro',
        description: 'A bonsai tree in a ceramic pot. The miniature scene deserves careful depth — use f/8 to keep the whole tree sharp.',
        image: 'images/bonsai.jpg',
        idealSettings: { iso: 1, aperture: 5, shutter: 9, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Side lighting accentuates the gnarled texture of the trunk','f/8 brings the entire miniature tree into focus','Clean, simple backgrounds let the bonsai be the subject','Shoot at tree-level, not from above — it looks more like a real tree']
    },
    {
        id: 'surfer',
        title: 'Surfer on a Big Wave',
        category: 'Sports',
        description: 'The surfer is moving fast AND the water is constantly changing. You need an ultra-fast shutter to freeze both the athlete and the wave spray.',
        image: 'images/surfer.jpg',
        idealSettings: { iso: 2, aperture: 2, shutter: 14, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['1/500s minimum; 1/1000s+ to freeze spray droplets','A telephoto lens (400mm+) is used by surf photographers on the shore','Shoot from the water or a pier for dramatic wave-level angles','Anticipate the best moment — reaction is always too late']
    },
    {
        id: 'product_glass',
        title: 'Product / Glassware',
        category: 'Still Life',
        description: 'Studio product photography of glassware. A controlled environment means you can go ISO 100, use any aperture, and take your time.',
        image: 'images/product_glass.jpg',
        idealSettings: { iso: 0, aperture: 4, shutter: 9, wb: 3 },
        acceptableRange: { iso: 0, aperture: 1, shutter: 2, wb: 1 },
        hasMotion: false, needsSharpBackground: false,
        idealWBName: 'Daylight/Studio',
        tips: ['ISO 100 always in a controlled studio — no noise ever','f/5.6 is typical for product shots: sharp but slightly separated','Use a lightbox or softboxes for even, glare-free illumination on glass','A black card opposite the light source creates a defining dark edge on glass']
    },
    {
        id: 'aurora_landscape',
        title: 'Aurora Over Mountains',
        category: 'Night',
        description: 'The aurora over a snowy mountain ridge. A landscape night shot requiring a balance: fast enough to avoid star trails, slow enough to record the aurora.',
        image: 'images/aurora.jpg',
        idealSettings: { iso: 5, aperture: 1, shutter: 1, wb: 4 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 2, wb: 2 },
        hasMotion: false, needsSharpBackground: true,
        idealWBName: 'Shade/Warm (subtle)',
        tips: ['Stick to the "500 Rule" for shutter to avoid star trails','f/2 lets the most light in for the snow-lit foreground','ISO 3200 captures the faint aurora without too much noise','A warm WB makes the snow foreground look more natural']
    },
    {
        id: 'street_candid',
        title: 'Street Candid Portrait',
        category: 'Street',
        description: 'A candid street portrait: a stranger walking by in interesting light. Shoot fast, be discreet, get the story of their face.',
        image: 'images/bicycle_street.jpg',
        idealSettings: { iso: 2, aperture: 2, shutter: 12, wb: 3 },
        acceptableRange: { iso: 1, aperture: 1, shutter: 1, wb: 1 },
        hasMotion: true, needsSharpBackground: false,
        idealWBName: 'Daylight',
        tips: ['Pre-set your exposure before lifting the camera','f/2.8 blurs the busy street background','1/250s is fast enough to freeze a walking person','Zone focusing (pre-focus at ~3m) lets you shoot instantly']
    }
];
